type: preprocessor
tune_mode: params
pipeline:
  - type: feature.cell
    target: WeightedFeaturePCA
    params:
      n_components: 400
      out: feature.cell
    params_to_tune:
      feat_norm_mode:
        values:
          - null
          - normalize
          - standardize
          - minmax
          - l2
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc  # val/acc
    goal: maximize
