type: preprocessor
tune_mode: pipeline
pipeline:
  - type: feature.cell
    include:
      - WeightedFeaturePCA
      - CellPCA
      - CellSVD
    params:
    #It is suggested to change to common_params
      out: feature.cell
    default_params:
      CellSVD:
        n_components: 400
      CellPCA:
        n_components: 400
      WeightedFeaturePCA:
        n_components: 400
        split_name: train
  # -type: filter.gene
  #   include:
  #     - FilterGenesTopK
  #     - FilterGenesPercentile
  #   params
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc  # val/acc
    goal: maximize
