---
type: preprocessor
tune_mode: pipeline_params
pipeline_tuning_top_k: 3
parameter_tuning_freq_n: 20
pipeline:
  - type: filter.gene
    include:
      - FilterGenesPercentile
      - FilterGenesScanpyOrder
      - FilterGenesPlaceHolder
    default_params:
      FilterGenesScanpyOrder:
        order: [min_counts, min_cells, max_counts, max_cells]
        min_counts: 1270
        max_counts: 310000
        min_cells: 0.01
        max_cells: 0.99
  - type: filter.cell
    include: [FilterCellsScanpyOrder, FilterCellsPlaceHolder]
    default_params:
      FilterCellsScanpyOrder:
        order: [min_counts, min_genes, max_counts, max_genes]
        min_counts: 840
        max_counts: 8000
        min_genes: 0.01
        max_genes: 0.99
  - type: misc
    target: SaveRaw
  - type: normalize
    include:
      - ColumnSumNormalize
      - ScTransform
      - Log1P
      - NormalizeTotal
      - NormalizePlaceHolder
      - NormalizeTotalLog1P
    default_params:
      ScTransform:
        processes_num: 8
  - type: filter.gene
    include:
      - HighlyVariableGenesLogarithmizedByMeanAndDisp
      - HighlyVariableGenesRawCount
      - HighlyVariableGenesLogarithmizedByTopGenes
      - FilterGenesTopK
      - FilterGenesRegression
      - FilterGenesPlaceHolder
    default_params:
      FilterGenesTopK:
        num_genes: 200
      FilterGenesRegression:
        num_genes: 200
      HighlyVariableGenesRawCount:
        n_top_genes: 200
      HighlyVariableGenesLogarithmizedByTopGenes:
        n_top_genes: 200
  - type: misc
    target: UpdateRaw
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: [None, None, n_counts]
        feature_channel_type: [X, raw_X, obs]
        label_channel: Group
wandb:
  entity: xzy11632
  project: dance-dev
  method: grid
  metric:
    name: acc
    goal: maximize
