type: preprocessor
tune_mode: pipeline_params
pipeline_tuning_top_k: 3
parameter_tuning_freq_n: 20
pipeline:
  - type: filter.gene
    include:
      - FilterGenesPercentile
      - FilterGenesScanpyOrder
      - FilterGenesPlaceHolder
    default_params:
      FilterGenesScanpyOrder:
        order: ["min_counts", "min_cells", "max_counts", "max_cells"]
        min_counts: 0.01
        max_counts: 0.99
        min_cells: 0.01
        max_cells: 0.99
  - type: normalize
    include:
      - ScaleFeature
      - ScTransform
      - Log1P
      - NormalizeTotal
      - NormalizePlaceHolder
    default_params:
      ScTransform:
        processes_num: 8
  - type: filter.gene
    include:
      - HighlyVariableGenesLogarithmizedByMeanAndDisp
      - HighlyVariableGenesRawCount
      - HighlyVariableGenesLogarithmizedByTopGenes
      - FilterGenesTopK
      - FilterGenesRegression
      # - FilterGenesNumberPlaceHolder
    default_params:
      FilterGenesTopK:
        num_genes: 3000
      FilterGenesRegression:
        num_genes: 3000
      HighlyVariableGenesRawCount:
        n_top_genes: 3000
      HighlyVariableGenesLogarithmizedByTopGenes:
        n_top_genes: 3000
  - type: feature.cell
    include:
      - WeightedFeaturePCA
      - WeightedFeatureSVD
      # - FeatureCellPlaceHolder
    params:
      out: feature.cell
      log_level: INFO
    default_params:
      WeightedFeaturePCA:
        split_name: train
      WeightedFeatureSVD:
        split_name: train
  - type: graph.cell
    target: CellFeatureGraph
    params:
      cell_feature_channel: feature.cell
  - type: misc
    target: SetConfig
    params:
      config_dict:
        label_channel: cell_type
wandb:
  entity: xzy11632
  project: dance-dev
  method: grid #try grid to provide a comprehensive search
  metric:
    name: acc  # val/acc
    goal: maximize
