---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: FilterGenesPlaceHolder
  - type: normalize
    target: NormalizePlaceHolder
  - type: filter.gene
    target: HighlyVariableGenesRawCount
    params_to_tune:
      n_top_genes:
        min: 100
        max: 10000
      span:
        min: 0.1
        max: 0.6
  - type: feature.cell
    target: WeightedFeatureSVD
    params:
      out: feature.cell
      log_level: INFO
    params_to_tune:
      n_components:
        min: 100
        max: 1000
      feat_norm_mode:
        values: [null, normalize, standardize, minmax, l2]
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
