type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: HighlyVariableGenesLogarithmizedByMeanAndDisp
    params_to_tune:
      min_disp:
        min: 0.05
        max: 0.5
      max_disp:
        min: 1.0
        max: 100.0
      min_mean:
        min: 0.0
        max: 0.0125
      max_mean:
        min: 3.0
        max: 20.0
      n_bins:
        min: 10
        max: 30
      flavor:
        values:
          - seurat
          - cell_ranger
  - type: feature.cell
    target: CellSVD
    params:
      out: feature.cell
    params_to_tune:
      n_components:
        min: 100
        max: 1000
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc  # val/acc
    goal: maximize
