type: preprocessor
tune_mode: pipeline
pipeline:
  - type: normalize
    include:
      - ScaleFeature
      - ScTransform
      - Log1P
      - NormalizeTotal
    default_params:
      ScTransform:
        min_cells: 2
        n_genes: 3000
        bin_size: 200
  - type: feature.cell
    include:
      - WeightedFeaturePCA
      - CellPCA
      - CellSVD
      - GaussRandProjFeature
    params:
      n_components: 400
      out: feature.cell
      log_level: INFO
    default_params:
      WeightedFeaturePCA:
        split_name: train
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: grid
  metric:
    name: acc
    goal: maximize
