---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: FilterGenesPlaceHolder
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
  - type: filter.gene
    target: FilterGenesRegression
    params_to_tune:
      method:
        values: [enclasc, seurat3, scmap]
      num_genes:
        min: 100
        max: 10000
  - type: feature.cell
    target: FeatureCellPlaceHolder
    params:
      out: feature.cell
      log_level: INFO
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
