---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.cell
    target: FilterCellTransform
    params:
      species: human
      image_save_path: ../figures/human_melanoma_data/
      log_level: INFO
  - type: filter.gene
    target: FilterGenesScanpyOrder
    params:
      order: [min_counts, min_cells]
      min_counts: 5
      min_cells: 3
  - type: filter.cell
    target: ScrubletTransform
    params:
      image_save_path: ../figures/human_melanoma_data/
  - type: filter.gene
    target: FilterGenesTopK
    params:
      num_genes: 2000
      mode: var
  - type: split.entry
    target: CellwiseMaskData
    params:
      add_test_mask: true
  - type: normalize
    target: ScTransform
    params_to_tune:
      min_cells:
        min: 1
        max: 10
      gmean_eps:
        min: 1
        max: 10
      n_genes:
        min: 1000
        max: 3000
      n_cells:
        values: [null, 1, 10, 100]
      bin_size:
        min: 300
        max: 800
      bw_adjust:
        min: 1.0
        max: 5.0
    params:
      processes_num: 8
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: [train_mask, valid_mask, test_mask]
        feature_channel_type: [layers, layers, layers]
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: MRE
    goal: minimize
