---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: FilterGenesPlaceHolder
  - type: normalize
    target: NormalizeTotalLog1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
      target_sum:
        values: [null, 1000.0, 10000.0, 100000.0, 1000000.0]
      max_fraction:
        values: [0.01, 0.05, 0.5, 0.7, 1.0]
  - type: filter.gene
    target: FilterGenesNumberPlaceHolder
  - type: feature.cell
    target: SCNFeature
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: SCNFeature
        label_channel: cell_type
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
