---
type: preprocessor
tune_mode: params
pipeline:
  - type: pseudobulk
    target: CellTopicProfile
    params:
      split_name: ref
      method: mean
  - type: filter.gene
    target: FilterGenesMatch
    params:
      prefixes: [ERCC, MT-]
  - type: filter.gene
    target: FilterGenesCommon
    params:
      split_keys: [ref, test]
  - type: filter.gene
    target: FilterGenesMarker
  - type: filter.gene
    target: FilterGenesPercentile
    params_to_tune:
      min_val:
        min: 1
        max: 10
      max_val:
        min: 95
        max: 99
      mode:
        values: [sum, var, cv, rv]
  - type: normalize
    target: ScTransform
    params_to_tune:
      min_cells:
        min: 1
        max: 10
      gmean_eps:
        min: 1
        max: 10
      n_genes:
        min: 1000
        max: 3000
      n_cells:
        values: [null, 1, 10, 100]
      bin_size:
        min: 300
        max: 800
      bw_adjust:
        min: 1.0
        max: 5.0
    params:
      processes_num: 8
  - type: filter.gene
    target: HighlyVariableGenesLogarithmizedByMeanAndDisp
    params_to_tune:
      min_disp:
        min: 0.05
        max: 0.5
      max_disp:
        min: 1.0
        max: 100.0
      min_mean:
        min: 0.0
        max: 0.0125
      max_mean:
        min: 3.0
        max: 20.0
      n_bins:
        min: 10
        max: 30
      flavor:
        values: [seurat, cell_ranger]
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: [null, spatial]
        feature_channel_type: [X, obsm]
        label_channel: cell_type_portion
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: MSE
    goal: minimize
