type: preprocessor
tune_mode: params
pipeline:
  - type: normalize
    target: NormalizeTotal
    params_to_tune:
      target_sum:
        values:
          - null
          - 1000.0
          - 10000.0
          - 100000.0
          - 1000000.0
      max_fraction:
        values:
          - 0.01
          - 0.05
          - 0.5
          - 0.7
          - 1.0
  - type: filter.gene
    target: HighlyVariableGenesRawCount
    params_to_tune:
      n_top_genes:
        min: 100
        max: 2000
      span:
        min: 0.1
        max: 0.6
  - type: feature.cell
    target: SCNFeature
    params:
      num_top_genes: 10
      num_top_gene_pairs: 25
      alpha2: 0.0005
      mu: 1
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: SCNFeature
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
