type: preprocessor
tune_mode: pipeline
pipeline:
  - type: normalize
    include:
      - ScaleFeature
      - ScTransform
      - Log1P
      - NormalizeTotal
    default_params:
      ScTransform:
        min_cells: 2
        n_genes: 3000
        bin_size: 200
  - type: misc
    target: SetConfig
    params:
      config_dict:
        label_channel: cell_type
wandb:
  entity: danceteam
  project: dance-dev
  method: grid
  metric:
    name: acc
    goal: maximize
