---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: FilterGenesPlaceHolder
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
  - type: filter.gene
    target: HighlyVariableGenesLogarithmizedByTopGenes
    params_to_tune:
      n_top_genes:
        min: 100
        max: 10000
      n_bins:
        min: 10
        max: 30
      flavor:
        values: [seurat, cell_ranger]
  - type: feature.cell
    target: CellPCA
    params:
      out: feature.cell
      log_level: INFO
    params_to_tune:
      n_components:
        min: 100
        max: 1000
      svd_solver:
        values: [auto, full, arpack, randomized]
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: feature.cell
        label_channel: cell_type
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
