---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: FilterGenesScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_cells
            - max_counts
            - max_cells
          - - min_counts
            - min_cells
            - max_cells
            - max_counts
          - - min_counts
            - max_counts
            - min_cells
            - max_cells
          - - min_counts
            - max_counts
            - max_cells
            - min_cells
          - - min_counts
            - max_cells
            - min_cells
            - max_counts
          - - min_counts
            - max_cells
            - max_counts
            - min_cells
          - - min_cells
            - min_counts
            - max_counts
            - max_cells
          - - min_cells
            - min_counts
            - max_cells
            - max_counts
          - - min_cells
            - max_counts
            - min_counts
            - max_cells
          - - min_cells
            - max_counts
            - max_cells
            - min_counts
          - - min_cells
            - max_cells
            - min_counts
            - max_counts
          - - min_cells
            - max_cells
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_cells
            - max_cells
          - - max_counts
            - min_counts
            - max_cells
            - min_cells
          - - max_counts
            - min_cells
            - min_counts
            - max_cells
          - - max_counts
            - min_cells
            - max_cells
            - min_counts
          - - max_counts
            - max_cells
            - min_counts
            - min_cells
          - - max_counts
            - max_cells
            - min_cells
            - min_counts
          - - max_cells
            - min_counts
            - min_cells
            - max_counts
          - - max_cells
            - min_counts
            - max_counts
            - min_cells
          - - max_cells
            - min_cells
            - min_counts
            - max_counts
          - - max_cells
            - min_cells
            - max_counts
            - min_counts
          - - max_cells
            - max_counts
            - min_counts
            - min_cells
          - - max_cells
            - max_counts
            - min_cells
            - min_counts
      min_counts:
        min: 3
        max: 500
      min_cells:
        min: 0.0
        max: 0.1
      max_counts:
        min: 0.9
        max: 1.0
      max_cells:
        min: 0.95
        max: 1.0
  - type: filter.cell
    target: FilterCellsScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_genes
            - max_counts
            - max_genes
          - - min_counts
            - min_genes
            - max_genes
            - max_counts
          - - min_counts
            - max_counts
            - min_genes
            - max_genes
          - - min_counts
            - max_counts
            - max_genes
            - min_genes
          - - min_counts
            - max_genes
            - min_genes
            - max_counts
          - - min_counts
            - max_genes
            - max_counts
            - min_genes
          - - min_genes
            - min_counts
            - max_counts
            - max_genes
          - - min_genes
            - min_counts
            - max_genes
            - max_counts
          - - min_genes
            - max_counts
            - min_counts
            - max_genes
          - - min_genes
            - max_counts
            - max_genes
            - min_counts
          - - min_genes
            - max_genes
            - min_counts
            - max_counts
          - - min_genes
            - max_genes
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_genes
            - max_genes
          - - max_counts
            - min_counts
            - max_genes
            - min_genes
          - - max_counts
            - min_genes
            - min_counts
            - max_genes
          - - max_counts
            - min_genes
            - max_genes
            - min_counts
          - - max_counts
            - max_genes
            - min_counts
            - min_genes
          - - max_counts
            - max_genes
            - min_genes
            - min_counts
          - - max_genes
            - min_counts
            - min_genes
            - max_counts
          - - max_genes
            - min_counts
            - max_counts
            - min_genes
          - - max_genes
            - min_genes
            - min_counts
            - max_counts
          - - max_genes
            - min_genes
            - max_counts
            - min_counts
          - - max_genes
            - max_counts
            - min_counts
            - min_genes
          - - max_genes
            - max_counts
            - min_genes
            - min_counts
      min_counts:
        min: 0.0
        max: 0.05
      min_genes:
        min: 0.0
        max: 0.05
      max_counts:
        min: 0.95
        max: 1.0
      max_genes:
        min: 0.95
        max: 1.0
  - type: misc
    target: SaveRaw
  - type: normalize
    target: NormalizeTotalLog1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
      target_sum:
        values: [null, 1000.0, 10000.0, 100000.0, 1000000.0]
      max_fraction:
        values: [0.01, 0.05, 0.5, 0.7, 1.0]
  - type: filter.gene
    target: HighlyVariableGenesLogarithmizedByTopGenes
    params_to_tune:
      n_top_genes:
        min: 100
        max: 10000
      n_bins:
        min: 10
        max: 30
      flavor:
        values: [seurat, cell_ranger]
  - type: misc
    target: UpdateRaw
  - type: feature.cell
    target: WeightedFeatureSVD
    params:
      out: feature.cell
      log_level: INFO
    params_to_tune:
      n_components:
        min: 100
        max: 1000
      feat_norm_mode:
        values: [null, normalize, standardize, minmax, l2]
  - type: graph.cell
    target: NeighborGraph
    params:
      channel: feature.cell
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_channel: [NeighborGraph, None, None, n_counts]
        feature_channel_type: [obsp, X, raw_X, obs]
        label_channel: Group
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: acc
    goal: maximize
