---
type: preprocessor
tune_mode: params
pipeline:
  - type: filter.gene
    target: FilterGenesScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_cells
            - max_counts
            - max_cells
          - - min_counts
            - min_cells
            - max_cells
            - max_counts
          - - min_counts
            - max_counts
            - min_cells
            - max_cells
          - - min_counts
            - max_counts
            - max_cells
            - min_cells
          - - min_counts
            - max_cells
            - min_cells
            - max_counts
          - - min_counts
            - max_cells
            - max_counts
            - min_cells
          - - min_cells
            - min_counts
            - max_counts
            - max_cells
          - - min_cells
            - min_counts
            - max_cells
            - max_counts
          - - min_cells
            - max_counts
            - min_counts
            - max_cells
          - - min_cells
            - max_counts
            - max_cells
            - min_counts
          - - min_cells
            - max_cells
            - min_counts
            - max_counts
          - - min_cells
            - max_cells
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_cells
            - max_cells
          - - max_counts
            - min_counts
            - max_cells
            - min_cells
          - - max_counts
            - min_cells
            - min_counts
            - max_cells
          - - max_counts
            - min_cells
            - max_cells
            - min_counts
          - - max_counts
            - max_cells
            - min_counts
            - min_cells
          - - max_counts
            - max_cells
            - min_cells
            - min_counts
          - - max_cells
            - min_counts
            - min_cells
            - max_counts
          - - max_cells
            - min_counts
            - max_counts
            - min_cells
          - - max_cells
            - min_cells
            - min_counts
            - max_counts
          - - max_cells
            - min_cells
            - max_counts
            - min_counts
          - - max_cells
            - max_counts
            - min_counts
            - min_cells
          - - max_cells
            - max_counts
            - min_cells
            - min_counts
      min_counts:
        min: 3
        max: 500
      min_cells:
        min: 0.0
        max: 0.1
      max_counts:
        min: 0.9
        max: 1.0
      max_cells:
        min: 0.95
        max: 1.0
    params:
      mod: mod1
  - type: filter.gene
    target: FilterGenesScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_cells
            - max_counts
            - max_cells
          - - min_counts
            - min_cells
            - max_cells
            - max_counts
          - - min_counts
            - max_counts
            - min_cells
            - max_cells
          - - min_counts
            - max_counts
            - max_cells
            - min_cells
          - - min_counts
            - max_cells
            - min_cells
            - max_counts
          - - min_counts
            - max_cells
            - max_counts
            - min_cells
          - - min_cells
            - min_counts
            - max_counts
            - max_cells
          - - min_cells
            - min_counts
            - max_cells
            - max_counts
          - - min_cells
            - max_counts
            - min_counts
            - max_cells
          - - min_cells
            - max_counts
            - max_cells
            - min_counts
          - - min_cells
            - max_cells
            - min_counts
            - max_counts
          - - min_cells
            - max_cells
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_cells
            - max_cells
          - - max_counts
            - min_counts
            - max_cells
            - min_cells
          - - max_counts
            - min_cells
            - min_counts
            - max_cells
          - - max_counts
            - min_cells
            - max_cells
            - min_counts
          - - max_counts
            - max_cells
            - min_counts
            - min_cells
          - - max_counts
            - max_cells
            - min_cells
            - min_counts
          - - max_cells
            - min_counts
            - min_cells
            - max_counts
          - - max_cells
            - min_counts
            - max_counts
            - min_cells
          - - max_cells
            - min_cells
            - min_counts
            - max_counts
          - - max_cells
            - min_cells
            - max_counts
            - min_counts
          - - max_cells
            - max_counts
            - min_counts
            - min_cells
          - - max_cells
            - max_counts
            - min_cells
            - min_counts
      min_counts:
        min: 3
        max: 500
      min_cells:
        min: 0.0
        max: 0.1
      max_counts:
        min: 0.9
        max: 1.0
      max_cells:
        min: 0.95
        max: 1.0
    params:
      mod: mod2
  - type: misc
    target: AlignMod
  - type: normalize
    target: tfidfTransform
    params:
      mod: mod1
  - type: normalize
    target: NormalizePlaceHolder
    params:
      mod: mod2
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
    params:
      mod: mod1
  - type: normalize
    target: Log1P
    params_to_tune:
      base:
        min: 1.0
        max: 10.0
    params:
      mod: mod2
  - type: filter.gene
    target: HighlyVariableGenesLogarithmizedByMeanAndDisp
    params_to_tune:
      min_disp:
        min: 0.05
        max: 0.5
      max_disp:
        min: 1.0
        max: 100.0
      min_mean:
        min: 0.0
        max: 0.0125
      max_mean:
        min: 3.0
        max: 20.0
      n_bins:
        min: 10
        max: 30
      flavor:
        values: [seurat, cell_ranger]
    params:
      mod: mod1
      channel: counts
      channel_type: layers
  - type: filter.gene
    target: FilterGenesNumberPlaceHolder
    params:
      mod: mod2
      channel: counts
      channel_type: layers
  - type: filter.cell
    target: FilterCellsPlaceHolder
    params:
      mod: mod1
  - type: filter.cell
    target: FilterCellsScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_genes
            - max_counts
            - max_genes
          - - min_counts
            - min_genes
            - max_genes
            - max_counts
          - - min_counts
            - max_counts
            - min_genes
            - max_genes
          - - min_counts
            - max_counts
            - max_genes
            - min_genes
          - - min_counts
            - max_genes
            - min_genes
            - max_counts
          - - min_counts
            - max_genes
            - max_counts
            - min_genes
          - - min_genes
            - min_counts
            - max_counts
            - max_genes
          - - min_genes
            - min_counts
            - max_genes
            - max_counts
          - - min_genes
            - max_counts
            - min_counts
            - max_genes
          - - min_genes
            - max_counts
            - max_genes
            - min_counts
          - - min_genes
            - max_genes
            - min_counts
            - max_counts
          - - min_genes
            - max_genes
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_genes
            - max_genes
          - - max_counts
            - min_counts
            - max_genes
            - min_genes
          - - max_counts
            - min_genes
            - min_counts
            - max_genes
          - - max_counts
            - min_genes
            - max_genes
            - min_counts
          - - max_counts
            - max_genes
            - min_counts
            - min_genes
          - - max_counts
            - max_genes
            - min_genes
            - min_counts
          - - max_genes
            - min_counts
            - min_genes
            - max_counts
          - - max_genes
            - min_counts
            - max_counts
            - min_genes
          - - max_genes
            - min_genes
            - min_counts
            - max_counts
          - - max_genes
            - min_genes
            - max_counts
            - min_counts
          - - max_genes
            - max_counts
            - min_counts
            - min_genes
          - - max_genes
            - max_counts
            - min_genes
            - min_counts
      min_counts:
        min: 0.0
        max: 0.05
      min_genes:
        min: 0.0
        max: 0.05
      max_counts:
        min: 0.95
        max: 1.0
      max_genes:
        min: 0.95
        max: 1.0
    params:
      mod: mod2
  - type: filter.cell
    target: FilterCellsCommonMod
    params:
      mod1: mod1
      mod2: mod2
      sol: test_sol
  - type: filter.cell
    target: FilterCellsScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_genes
            - max_counts
            - max_genes
          - - min_counts
            - min_genes
            - max_genes
            - max_counts
          - - min_counts
            - max_counts
            - min_genes
            - max_genes
          - - min_counts
            - max_counts
            - max_genes
            - min_genes
          - - min_counts
            - max_genes
            - min_genes
            - max_counts
          - - min_counts
            - max_genes
            - max_counts
            - min_genes
          - - min_genes
            - min_counts
            - max_counts
            - max_genes
          - - min_genes
            - min_counts
            - max_genes
            - max_counts
          - - min_genes
            - max_counts
            - min_counts
            - max_genes
          - - min_genes
            - max_counts
            - max_genes
            - min_counts
          - - min_genes
            - max_genes
            - min_counts
            - max_counts
          - - min_genes
            - max_genes
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_genes
            - max_genes
          - - max_counts
            - min_counts
            - max_genes
            - min_genes
          - - max_counts
            - min_genes
            - min_counts
            - max_genes
          - - max_counts
            - min_genes
            - max_genes
            - min_counts
          - - max_counts
            - max_genes
            - min_counts
            - min_genes
          - - max_counts
            - max_genes
            - min_genes
            - min_counts
          - - max_genes
            - min_counts
            - min_genes
            - max_counts
          - - max_genes
            - min_counts
            - max_counts
            - min_genes
          - - max_genes
            - min_genes
            - min_counts
            - max_counts
          - - max_genes
            - min_genes
            - max_counts
            - min_counts
          - - max_genes
            - max_counts
            - min_counts
            - min_genes
          - - max_genes
            - max_counts
            - min_genes
            - min_counts
      min_counts:
        min: 0.0
        max: 0.05
      min_genes:
        min: 0.0
        max: 0.05
      max_counts:
        min: 0.95
        max: 1.0
      max_genes:
        min: 0.95
        max: 1.0
    params:
      mod: meta1
  - type: filter.cell
    target: FilterCellsScanpyOrder
    params_to_tune:
      order:
        values:
          - - min_counts
            - min_genes
            - max_counts
            - max_genes
          - - min_counts
            - min_genes
            - max_genes
            - max_counts
          - - min_counts
            - max_counts
            - min_genes
            - max_genes
          - - min_counts
            - max_counts
            - max_genes
            - min_genes
          - - min_counts
            - max_genes
            - min_genes
            - max_counts
          - - min_counts
            - max_genes
            - max_counts
            - min_genes
          - - min_genes
            - min_counts
            - max_counts
            - max_genes
          - - min_genes
            - min_counts
            - max_genes
            - max_counts
          - - min_genes
            - max_counts
            - min_counts
            - max_genes
          - - min_genes
            - max_counts
            - max_genes
            - min_counts
          - - min_genes
            - max_genes
            - min_counts
            - max_counts
          - - min_genes
            - max_genes
            - max_counts
            - min_counts
          - - max_counts
            - min_counts
            - min_genes
            - max_genes
          - - max_counts
            - min_counts
            - max_genes
            - min_genes
          - - max_counts
            - min_genes
            - min_counts
            - max_genes
          - - max_counts
            - min_genes
            - max_genes
            - min_counts
          - - max_counts
            - max_genes
            - min_counts
            - min_genes
          - - max_counts
            - max_genes
            - min_genes
            - min_counts
          - - max_genes
            - min_counts
            - min_genes
            - max_counts
          - - max_genes
            - min_counts
            - max_counts
            - min_genes
          - - max_genes
            - min_genes
            - min_counts
            - max_counts
          - - max_genes
            - min_genes
            - max_counts
            - min_counts
          - - max_genes
            - max_counts
            - min_counts
            - min_genes
          - - max_genes
            - max_counts
            - min_genes
            - min_counts
      min_counts:
        min: 0.0
        max: 0.05
      min_genes:
        min: 0.0
        max: 0.05
      max_counts:
        min: 0.95
        max: 1.0
      max_genes:
        min: 0.95
        max: 1.0
    params:
      mod: meta2
  - type: filter.cell
    target: FilterCellsCommonMod
    params:
      mod1: meta1
      mod2: meta2
  - type: feature.cell
    target: FeatureCellPlaceHolder
    params:
      out: feature.cell
      log_level: INFO
      mod: mod1
  - type: feature.cell
    target: WeightedFeaturePCA
    params:
      out: feature.cell
      log_level: INFO
      mod: mod2
    params_to_tune:
      n_components:
        min: 100
        max: 1000
      feat_norm_mode:
        values: [null, normalize, standardize, minmax, l2]
  - type: misc
    target: SetConfig
    params:
      config_dict:
        feature_mod: [mod1, mod2, mod1, mod2]
        label_mod: mod1
        feature_channel_type: [obsm, obsm, layers, layers]
        feature_channel: [feature.cell, feature.cell, counts, counts]
        label_channel: labels
wandb:
  entity: xzy11632
  project: dance-dev
  method: bayes
  metric:
    name: ARI
    goal: maximize
