---
algorithms:
  cta_actinn:
    command: python main.py --species {species} --tissue {tissue} --train_dataset
      {dataset_id}  --filetype {filetype} --count {count} --device {device} > {dataset_id}/out.log
      2>&1 &
  cta_singlecellnet:
    command: python main.py --species {species} --tissue {tissue} --train_dataset
      {dataset_id}  --filetype {filetype} --count {count} > {dataset_id}/out.log 2>&1
      &
  cta_celltypist:
    command: python main.py --species {species} --tissue {tissue} --train_dataset
      {dataset_id}  --filetype {filetype} --count {count} > {dataset_id}/out.log 2>&1
      &
  cta_scdeepsort:
    command: python main.py --species {species} --tissue {tissue} --train_dataset
      {dataset_id}  --filetype {filetype} --count {count} --device {device} > {dataset_id}/out.log
      2>&1 &
