job: xzy11632/pytorch-cell_type_annotation_ACTINN_function_new/job-source-pytorch-cell_type_annotation_ACTINN_function_new-test_automl_test_automl_fun_job.py:latest
metric:
  goal: maximize
  name: scores
run_cap: 20
scheduler:
  job: xzy11632/pytorch-cell_type_annotation_ACTINN_function_new/job-OptunaScheduler:latest
  num_workers: 2
  docker_image: r:fcf2b32f 
  resource_args:
    local-container:
      env-file: "/home/zyxing/dance/web-variables.env"
  settings:        
    optuna_source: xzy11632/pytorch-cell_type_annotation_ACTINN_function_new/optuna-config:latest
    optuna_source_filename: test_automl/optuna_wandb.py
    pruner:
      args:
        n_min_trials: 1
        n_startup_trials: 2
        percentile: 0.25
      type: PercentilePruner
